import moment from "moment";
import TypesCompromissos from '../lib/TiposDeCompromissos';
import StatusCompromissos from '../lib/StatusCompromissos';

export default [
  //segunda
  {
    id: '3',
    type: TypesCompromissos.VISIT,
    at: moment().day(1),
    hour: '10:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Mario",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '1',
    type: TypesCompromissos.MEETING,
    at: moment().day(1),
    hour: '16:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Ronaldo",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '2',
    type: TypesCompromissos.VISIT,
    at: moment().day(1),
    hour: '17:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Rodrigo",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '20',
    type: TypesCompromissos.MEETING,
    at: moment().day(1),
    hour: '19:00',
    nomeEmpresa: "Banco Luso",
    nomeResponsavel: "Carlos",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  //terça
  {
    id: '4',
    type: TypesCompromissos.VISIT,
    at: moment().day(2),
    hour: '09:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Marcela",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '5',
    type: TypesCompromissos.MEETING,
    at: moment().day(2),
    hour: '13:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Cristiano",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '6',
    type: TypesCompromissos.MEETING,
    at: moment().day(2),
    hour: '15:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Carla",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  //quarta
  {
    id: '7',
    type: TypesCompromissos.VISIT,
    at: moment().day(3),
    hour: '13:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '8',
    type: TypesCompromissos.VISIT,
    at: moment().day(3),
    hour: '14:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '9',
    type: TypesCompromissos.VISIT,
    at: moment().day(3),
    hour: '20:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  // quinta
  {
    id: '10',
    type: TypesCompromissos.MEETING,
    at: moment().day(4),
    hour: '10:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '11',
    type: TypesCompromissos.MEETING,
    at: moment().day(4),
    hour: '16:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '12',
    type: TypesCompromissos.VISIT,
    at: moment().day(4),
    hour: '17:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  // sexta
  {
    id: '13',
    type: TypesCompromissos.MEETING,
    at: moment().day(5),
    hour: '09:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '14',
    type: TypesCompromissos.MEETING,
    at: moment().day(5),
    hour: '11:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
  {
    id: '15',
    type: TypesCompromissos.VISIT,
    at: moment().day(5),
    hour: '14:00',
    nomeEmpresa: "Impacta",
    nomeResponsavel: "Renato",
    address: {
      cep: "09990730",
      street: "Av. Paulista",
      number: "1234",
      city: "São Paulo",
      uf: "SP",
    },
    status: StatusCompromissos.PENDING,
  },
];
